// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk85wpR6spS5dtRyffiyGu72pOyqySsPI',
    appId: '1:726895934198:web:6bf982f8c44708741a8ad7',
    messagingSenderId: '726895934198',
    projectId: 'voice-and-text-translato-a7a09',
    authDomain: 'voice-and-text-translato-a7a09.firebaseapp.com',
    databaseURL: 'https://voice-and-text-translato-a7a09-default-rtdb.firebaseio.com',
    storageBucket: 'voice-and-text-translato-a7a09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8tEuf_Hltvsi90TF-2zWi1tWkuqzuNo',
    appId: '1:726895934198:android:ff23af7942cf831b1a8ad7',
    messagingSenderId: '726895934198',
    projectId: 'voice-and-text-translato-a7a09',
    databaseURL: 'https://voice-and-text-translato-a7a09-default-rtdb.firebaseio.com',
    storageBucket: 'voice-and-text-translato-a7a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDilqfFi_zIqauyTKsCSqtuGlJtMgZgmw8',
    appId: '1:726895934198:ios:6d37fb7dd534d5e41a8ad7',
    messagingSenderId: '726895934198',
    projectId: 'voice-and-text-translato-a7a09',
    databaseURL: 'https://voice-and-text-translato-a7a09-default-rtdb.firebaseio.com',
    storageBucket: 'voice-and-text-translato-a7a09.appspot.com',
    iosBundleId: 'com.example.voiceAndTextTranslator',
  );
}
